name: common_package
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  provider: ^6.0.2
  dio: ^4.0.4
  google_maps_flutter: ^2.1.1
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  carousel_slider: ^4.0.0
  geolocator: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
